LinearRegression:
  fit_intercept: [true, false]
  copy_X: [true, false]
  n_jobs: [null, -1, 1, 2, 4]
  positive: [true, false]

SVR:
  kernel: ["linear", "poly", "rbf", "sigmoid"]
  degree: [2, 3, 4, 5]
  gamma: ["scale", "auto", 0.001, 0.01, 0.1, 1]
  coef0: [0.0, 0.1, 0.5, 1.0]
  C: [0.1, 1, 10, 100]
  epsilon: [0.01, 0.1, 0.5, 1.0]
  shrinking: [true, false]
  cache_size: [200, 500, 1000]
  verbose: [false, true]
  max_iter: [-1, 1000, 5000, 10000]

KNeighborsRegressor:
  n_neighbors: [1, 2, 3, 4, 5,10, 50]
  weights: ["uniform", "distance"]
  algorithm: ["auto", "ball_tree", "kd_tree", "brute"]
  leaf_size: [10, 20, 30, 40, 50, 60, 70, 80, 90]
  p: [1, 2]
  metric: ["minkowski", "euclidean", "manhattan", "chebyshev"]
  metric_params: [null]
  n_jobs: [null, -1]

DecisionTreeRegressor:
  criterion: ["squared_error", "friedman_mse", "absolute_error", "poisson"]
  splitter: ["best", "random"]
  max_depth: [null, 2, 3, 10, 50]
  min_samples_split: [2, 5, 10, 20]
  min_samples_leaf: [1, 2, 5, 10]
  min_weight_fraction_leaf: [0.0, 0.1, 0.2]
  max_features: [null, "sqrt", "log2"]
  random_state: [null]
  max_leaf_nodes: [null, 10, 50, 100]
  min_impurity_decrease: [0.0, 0.01, 0.1]
  ccp_alpha: [0.0, 0.01, 0.1]
  monotonic_cst: [null]

RandomForestRegressor:
  n_estimators: [50, 100, 200, 500]
  criterion: ["squared_error", "absolute_error", "friedman_mse", "poisson"]
  max_depth: [null, 5, 10, 15, 20, 50]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 2, 5, 10]
  min_weight_fraction_leaf: [0.0, 0.1]
  max_features: ["sqrt", "log2", null, 0.5, 1.0]
  bootstrap: [true, false]
  oob_score: [true, false]
  n_jobs: [null, -1]
  random_state: [null]
  verbose: [0, 1]
  warm_start: [true, false]
  ccp_alpha: [0.0, 0.01]
  max_samples: [null, 0.5, 0.8, 1.0]
  monotonic_cst: [null]

AdaBoostRegressor:
  estimator: [null]
  n_estimators: [50, 100, 200, 500]
  learning_rate: [0.01, 0.1, 0.5, 1.0]
  loss: ["linear", "square", "exponential"]
  random_state: [null]

GradientBoostingRegressor:
  loss: ["squared_error", "absolute_error", "huber", "quantile"]
  learning_rate: [0.01, 0.05, 0.1, 0.2]
  n_estimators: [100, 200, 500]
  subsample: [0.5, 0.8, 1.0]
  criterion: ["friedman_mse", "squared_error"]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 2, 5]
  max_depth: [3, 5, 10]
  max_features: [null, "sqrt", "log2"]
  alpha: [0.9, 0.95, 0.99]
  validation_fraction: [0.1, 0.2]
  n_iter_no_change: [null, 5, 10]

  warm_start: [true, false]
  ccp_alpha: [0.0, 0.01]

XGBoostRegressor:
  booster: ["gbtree", "gblinear", "dart"]
  eta: [0.01, 0.05, 0.1, 0.3]
  max_depth: [3, 4,10, 14]
  min_child_weight: [1, 2, 5, 10]
  subsample: [0.5, 0.8, 1.0]
  colsample_bytree: [0.5, 0.8, 1.0]
  colsample_bylevel: [0.5, 0.8, 1.0]
  colsample_bynode: [0.5, 0.8, 1.0]
  lambda: [0.0, 0.1, 1.0, 10.0]
  alpha: [0.0, 0.1, 1.0, 10.0]
  gamma: [0.0, 0.1, 1.0]
  eval_metric: ["rmse", "mae", "rmsle"]
  n_estimators: [100, 200, 500]
  seed: [null]